version: "3.8"

services:
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network
  
  backend:
    build: ./backend
    image: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data:cached
    networks:
      - network

networks:
  network:
    driver: bridge
